language: php
dist: trusty

matrix:
  fast_finish: true
  include:
    - env: TEST_DIR=. PHP_CS_FIXER=true PHPSTAN=true
      php: 7.2
    - env: TEST_DIR=. COMPOSER_FLAGS="--prefer-lowest"
      php: 7.2
    - env: TEST_DIR=.
      php: 7.3
    - env: TEST_DIR=.
      php: 7.4snapshot
    - env: TEST_DIR=tests/integration/apache
      php: 7.2
      dist: trusty
      sudo: required
      services:
      - docker
    - env: TEST_DIR=tests/integration/guzzle/3
      php: 7.2
# Guzzle 4 is not compatible with PHP >= 7.1 due to an error in the code that was only fixed in Guzzle 5.
# See: https://github.com/guzzle/guzzle/pull/1393
#    - env: TEST_DIR=tests/integration/guzzle/4
#      php: 7.2
    - env: TEST_DIR=tests/integration/guzzle/5
      php: 7.2
    - env: TEST_DIR=tests/integration/guzzle/6
      php: 7.2
    - env: TEST_DIR=tests/integration/soap
      php: 7.2
  allow_failures:
    - php: 7.4snapshot

before_install:
  - composer self-update

install:
  - composer update --prefer-source -o $COMPOSER_FLAGS
  - PHPUNIT_BIN=$(pwd)/vendor/bin/phpunit
  - cd ${TEST_DIR}
  - composer update --prefer-source -o $COMPOSER_FLAGS

script:
  - $PHPUNIT_BIN --coverage-clover=coverage.clover
  - if [ "${PHP_CS_FIXER}" = "true" ]; then wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar && php ./php-cs-fixer-v2.phar fix --dry-run --diff $TRAVIS_BUILD_DIR; fi
  - if [ "${PHPSTAN}" = "true" ]; then composer require --dev phpstan/phpstan ^0.10 && composer phpstan; fi

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - vendor
    - tests/integration/guzzle/3/vendor
#    - tests/integration/guzzle/4/vendor
    - tests/integration/guzzle/5/vendor
    - tests/integration/guzzle/6/vendor
    - tests/integration/soap/vendor
    - $HOME/.composer/cache
